import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import { relative } from "node:path";

import {
  listFilesRecursive,
  pathExists,
  resolvePath,
} from "../core/file-system.js";
import type {
  CefrLevel,
  QaCheck,
  QaReport,
  RenderPayload,
  TopicPackage,
} from "../core/types.js";
import { nowIso } from "../core/dates.js";
import { validate } from "../core/validators.js";

export interface PackageQaInput {
  packageDir: string;
  topicPackage: TopicPackage;
  expectedLevels: CefrLevel[];
  runId?: string;
}

function check(
  checks: QaCheck[],
  id: string,
  passed: boolean,
  message: string,
  level?: CefrLevel,
  severity: QaCheck["severity"] = "error",
): void {
  checks.push({ id, passed, message, level, severity });
}

function requiredLevelArtifacts(packageDir: string, level: CefrLevel): string[] {
  const base = `${packageDir}/levels/${level}`;
  return [
    `${base}/level-package.json`,
    `${base}/script.txt`,
    `${base}/audio.mp3`,
    `${base}/subtitles.srt`,
    `${base}/subtitles.vtt`,
    `${base}/render-payload.json`,
    `${base}/video.mp4`,
    `${base}/youtube-metadata.json`,
    `${base}/instagram-metadata.json`,
  ];
}

function nonEmptySecretValues(): string[] {
  return Object.entries(process.env)
    .filter(([key, value]) => {
      return (
        /(token|secret|password|api[_-]?key|credential|refresh[_-]?token)/i.test(
          key,
        ) &&
        typeof value === "string" &&
        value.length >= 8
      );
    })
    .map(([, value]) => value as string);
}

async function findSecretLeak(packageDir: string): Promise<string | null> {
  const secretValues = nonEmptySecretValues();
  const suspiciousPatterns = [
    /\bsk-[A-Za-z0-9_-]{16,}\b/,
    /\bBearer\s+[A-Za-z0-9._-]{16,}\b/i,
  ];

  for (const file of await listFilesRecursive(packageDir)) {
    const content = await readFile(file);
    if (content.byteLength > 1_000_000) continue;
    const text = content.toString("utf8");
    if (secretValues.some((secret) => text.includes(secret))) {
      return relative(resolvePath(packageDir), file);
    }
    if (suspiciousPatterns.some((pattern) => pattern.test(text))) {
      return relative(resolvePath(packageDir), file);
    }
  }
  return null;
}

export async function runPackageQa(input: PackageQaInput): Promise<QaReport> {
  const { packageDir, topicPackage, expectedLevels, runId } = input;
  const checks: QaCheck[] = [];
  const schemaResult = validate("topic-package", topicPackage);

  check(
    checks,
    "topic-package-schema",
    schemaResult.valid,
    schemaResult.valid
      ? "Topic package matches its JSON Schema."
      : `Topic package schema errors: ${schemaResult.errors.length}`,
  );

  const actualLevels = topicPackage.levels.map((item) => item.level);
  const uniqueLevels = new Set(actualLevels);
  const expectedSet = new Set(expectedLevels);
  check(
    checks,
    "expected-levels",
    expectedLevels.every((level) => uniqueLevels.has(level)) &&
      uniqueLevels.size === expectedSet.size &&
      actualLevels.length === uniqueLevels.size,
    `Expected ${expectedLevels.join(", ")}; found ${actualLevels.join(", ")}.`,
  );

  const sceneIds = new Set(
    topicPackage.visualScenes.scenes.map((scene) => scene.sceneId),
  );
  check(
    checks,
    "shared-scenes-present",
    sceneIds.size > 0,
    `Shared visual manifest contains ${sceneIds.size} scene(s).`,
  );
  check(
    checks,
    "scene-order",
    topicPackage.visualScenes.scenes.every(
      (scene, index) => scene.order === index,
    ),
    "Shared scenes use a contiguous zero-based order.",
  );
  for (const scene of topicPackage.visualScenes.scenes) {
    const imageExists =
      typeof scene.imageRef === "string" && (await pathExists(scene.imageRef));
    check(
      checks,
      "shared-image-exists",
      imageExists,
      `${scene.sceneId} image ${imageExists ? "exists" : "is missing"}.`,
    );
    const imageHashValid =
      imageExists &&
      typeof scene.imageHash === "string" &&
      scene.imageHash ===
        createHash("sha256")
          .update(await readFile(resolvePath(scene.imageRef as string)))
          .digest("hex");
    check(
      checks,
      "shared-image-hash",
      scene.imageHash === undefined || imageHashValid,
      imageHashValid
        ? `${scene.sceneId} image hash matches its generated bytes.`
        : scene.imageHash === undefined
          ? `${scene.sceneId} image hash is unavailable in this legacy package.`
          : `${scene.sceneId} image hash does not match its bytes.`,
      undefined,
      scene.imageHash === undefined ? "warn" : "error",
    );
    const provenance = scene.imageProvenance;
    const provenanceSchema =
      provenance === undefined
        ? { valid: false, errors: [] }
        : validate("image-generation-result", provenance);
    check(
      checks,
      "image-provenance",
      provenanceSchema.valid &&
        provenance?.topicId === topicPackage.topicId &&
        provenance?.sceneId === scene.sceneId &&
        provenance?.moderation === "auto",
      provenanceSchema.valid
        ? `${scene.sceneId} has matching non-secret image provenance.`
        : `${scene.sceneId} image provenance is missing or invalid.`,
    );
  }

  for (const levelPackage of topicPackage.levels) {
    const level = levelPackage.level;
    check(
      checks,
      "topic-id-match",
      levelPackage.topicId === topicPackage.topicId,
      `Level topicId is ${levelPackage.topicId}.`,
      level,
    );
    check(
      checks,
      "level-badge-match",
      levelPackage.levelBadge.level === level,
      `Level badge is ${levelPackage.levelBadge.level}.`,
      level,
    );

    const scriptRefsValid = levelPackage.script.lines.every((line) =>
      sceneIds.has(line.sceneId),
    );
    check(
      checks,
      "script-scene-refs",
      scriptRefsValid,
      scriptRefsValid
        ? "All script lines reference shared scenes."
        : "Script contains an unknown scene reference.",
      level,
    );

    const subtitleRefsValid = levelPackage.subtitle.cues.every((cue) =>
      sceneIds.has(cue.sceneId),
    );
    const subtitleTimingValid = levelPackage.subtitle.cues.every(
      (cue) => cue.endMs > cue.startMs,
    );
    check(
      checks,
      "subtitle-scene-refs",
      subtitleRefsValid,
      subtitleRefsValid
        ? "All subtitle cues reference shared scenes."
        : "Subtitle contains an unknown scene reference.",
      level,
    );
    check(
      checks,
      "subtitle-timing",
      subtitleTimingValid,
      subtitleTimingValid
        ? "All subtitle cues have positive duration."
        : "Subtitle timing is invalid.",
      level,
    );
    const finalCue = levelPackage.subtitle.cues.at(-1);
    const durationAligned =
      finalCue !== undefined &&
      Math.abs(finalCue.endMs / 1000 - levelPackage.audio.durationSeconds) <= 0.25;
    check(
      checks,
      "audio-subtitle-duration",
      durationAligned,
      durationAligned
        ? "Subtitle end time matches audio duration."
        : "Subtitle end time does not match audio duration.",
      level,
    );

    for (const artifact of requiredLevelArtifacts(packageDir, level)) {
      const exists = await pathExists(artifact);
      check(
        checks,
        "artifact-exists",
        exists,
        `${artifact.replace(`${packageDir}/`, "")} ${exists ? "exists" : "is missing"}.`,
        level,
      );
    }

    const renderPayloadPath = `${packageDir}/levels/${level}/render-payload.json`;
    if (await pathExists(renderPayloadPath)) {
      const renderPayload = JSON.parse(
        await readFile(resolvePath(renderPayloadPath), "utf8"),
      ) as RenderPayload;
      const renderSchema = validate("render-payload", renderPayload);
      check(
        checks,
        "render-payload-schema",
        renderSchema.valid,
        renderSchema.valid
          ? "Render payload matches its JSON Schema."
          : `Render payload schema errors: ${renderSchema.errors.length}.`,
        level,
      );
      check(
        checks,
        "render-shared-manifest",
        JSON.stringify(renderPayload.visualScenes) ===
          JSON.stringify(topicPackage.visualScenes),
        "Render payload uses the topic shared visual manifest unchanged.",
        level,
      );
    }
  }

  const scriptVariants = new Set(
    topicPackage.levels.map((item) =>
      item.script.lines.map((line) => line.text).join("\n"),
    ),
  );
  check(
    checks,
    "level-scripts-distinct",
    scriptVariants.size === topicPackage.levels.length,
    "Each requested level has a distinct script.",
  );

  for (const commonArtifact of [
    `${packageDir}/common/visual-scenes.json`,
    `${packageDir}/common/image-manifest.json`,
  ]) {
    const exists = await pathExists(commonArtifact);
    check(
      checks,
      "common-artifact-exists",
      exists,
      `${commonArtifact.replace(`${packageDir}/`, "")} ${exists ? "exists" : "is missing"}.`,
    );
  }
  const manifestPath = `${packageDir}/common/image-manifest.json`;
  if (await pathExists(manifestPath)) {
    const manifest = JSON.parse(
      await readFile(resolvePath(manifestPath), "utf8"),
    );
    check(
      checks,
      "manifest-source-of-truth",
      JSON.stringify(manifest) === JSON.stringify(topicPackage.visualScenes),
      "On-disk image manifest matches the topic package shared manifest.",
    );
  }

  const leak = await findSecretLeak(packageDir);
  check(
    checks,
    "secret-leak",
    leak === null,
    leak === null ? "No secret-like value found in generated output." : `Potential secret found in ${leak}.`,
  );

  const errors = checks.filter(
    (item) => !item.passed && item.severity === "error",
  ).length;
  const warnings = checks.filter(
    (item) => !item.passed && item.severity === "warn",
  ).length;
  const passedCount = checks.filter((item) => item.passed).length;

  return {
    schemaVersion: 1,
    topicId: topicPackage.topicId,
    runId,
    generatedAt: nowIso(),
    passed: errors === 0,
    score: checks.length === 0 ? 0 : passedCount / checks.length,
    checks,
    summary: { errors, warnings },
  };
}
