/**
 * Centralized error codes for the application
 * These codes are used in API responses and can be mapped to user-friendly messages on the frontend
 */

const ERROR_CODES = {
  // Input validation errors
  INVALID_INPUT: 'INVALID_INPUT',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_PHONE: 'INVALID_PHONE',
  NAME_INVALID: 'NAME_INVALID',
  NAME_TOO_LONG: 'NAME_TOO_LONG',
  EMAIL_TOO_LONG: 'EMAIL_TOO_LONG',
  PASSWORD_TOO_LONG: 'PASSWORD_TOO_LONG',

  // Authentication errors
  EMAIL_IN_USE: 'EMAIL_IN_USE',
  PHONE_IN_USE: 'PHONE_IN_USE',
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
  PASSWORD_TOO_SHORT: 'PASSWORD_TOO_SHORT',
  PASSWORD_TOO_WEAK: 'PASSWORD_TOO_WEAK',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',

  // Token errors
  TOKEN_REQUIRED: 'TOKEN_REQUIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  MISSING_TOKEN: 'MISSING_TOKEN',

  // Rate limiting
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // Registration errors
  REGISTRATION_FAILED: 'REGISTRATION_FAILED',
  EMAIL_REQUIRED: 'EMAIL_REQUIRED',
  EMAIL_OR_SUB_REQUIRED: 'EMAIL_OR_SUB_REQUIRED',

  // Update errors
  UPDATE_FAILED: 'UPDATE_FAILED',
  CREATE_FAILED: 'CREATE_FAILED',
  DB_ERROR: 'DB_ERROR',

  // General errors
  SERVER_ERROR: 'SERVER_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR'
};

module.exports = ERROR_CODES;
